# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

steps:
- script: Rscript -e "install.packages(c('caret', 'readxl','rpart','dplyr','rpart.plot', 'ggplot2','tidyverse','zoo','lubridate','forecast','faraway','xts'), repos='http://cran.rstudio.com/')"
  displayName: 'Install R packages'

steps:
- script: Rscript "C:\Users\kmelton\OneDrive - High Technology Foundation\Desktop\temp prediction with ts.Rmd"
  displayName: 'Execute R script'
